name: Build and test

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - rostooling/setup-ros-docker:ubuntu-focal-ros-galactic-ros-base-latest
          - osrf/ros:galactic-desktop
    container:
      image: ${{ matrix.docker_image }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pip
        run: |
          apt-get -y update
          apt-get -y install python3-pip

      - name: Update colcon-package-selection
        run: |
          pip3 install -U colcon-package-selection

      - name: Search packages in this repository
        id: list_packages
        run: |
          echo ::set-output name=package_list::$(colcon list --names-only)

      - name: Run rosdep install
        run: |
          apt-get -y update
          rosdep update
          DEBIAN_FRONTEND=noninteractive rosdep install -y --from-paths . --ignore-src --rosdistro galactic

      - name: Run colcon build
        run: |
          . /opt/ros/galactic/setup.sh
          colcon build --event-handlers console_cohesion+ \
            --packages-above-and-dependencies package_name
